blank_issues_enabled: false
contact_links:
  - name: astro-polyglot Documentation
    url: https://astro-polyglot.vercel.app/
    about: Check the documentation for usage guides and API reference.
  - name: Starlight Documentation
    url: https://starlight.astro.build/
    about: General Starlight documentation and guides.
