/**
 * astro-polyglot — .NET XML Doc Utilities
 *
 * Shared utilities for .NET XML documentation-backed language handlers.
 * Provides XML doc parsing and project detection reused by
 * C#, VB.NET, and F# handlers.
 *
 * @module core/dotnet-xml-utils
 */

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve, extname, basename } from "node:path";
import type { ASTClass, ASTModule } from "./mdx-generator";

// ─── Types ─────────────────────────────────────────────────────────────────

export interface DotNetXmlMember {
  /** Full member name with prefix, e.g. "T:Namespace.Class" or "M:Namespace.Class.Method" */
  name: string;
  summary?: string;
  params?: { name: string; description?: string }[];
  returns?: string;
  remarks?: string;
  example?: string;
}

export interface DotNetXmlDoc {
  assemblyName?: string;
  members: DotNetXmlMember[];
}

export interface ProjectInfo {
  projectPath: string;
  language: string;
  targetFramework?: string;
  assemblyName?: string;
  sourceFiles: string[];
}

// ─── Project Detection ─────────────────────────────────────────────────────

const projectExtensions: Record<string, string> = {
  ".csproj": "csharp",
  ".fsproj": "fsharp",
  ".vbproj": "vbnet",
};

/**
 * Detect .NET project files in a directory.
 * Returns the first matching project file and its language.
 */
export function detectProject(dir: string): ProjectInfo | null {
  if (!existsSync(dir)) return null;

  const entries = readdirSync(dir);
  for (const entry of entries) {
    const ext = extname(entry);
    const language = projectExtensions[ext];
    if (language) {
      const fullPath = resolve(dir, entry);
      const content = readFileSync(fullPath, "utf-8");
      const tfm = content.match(/<TargetFramework[^>]*>([^<]+)<\/TargetFramework>/)?.[1];
      const aname =
        content.match(/<AssemblyName[^>]*>([^<]+)<\/AssemblyName>/)?.[1] ?? basename(entry, ext);
      return {
        projectPath: fullPath,
        language,
        targetFramework: tfm,
        assemblyName: aname,
        sourceFiles: [],
      };
    }
  }

  return null;
}

/**
 * Detect .NET project file from a path (file or directory).
 */
export function resolveProjectFile(projectPath: string): ProjectInfo | null {
  const resolved = resolve(projectPath);
  if (!existsSync(resolved)) return null;

  const st = statSync(resolved);
  if (st.isDirectory()) {
    return detectProject(resolved);
  }

  const ext = extname(resolved);
  const language = projectExtensions[ext];
  if (!language) return null;

  const content = readFileSync(resolved, "utf-8");
  const tfm = content.match(/<TargetFramework[^>]*>([^<]+)<\/TargetFramework>/)?.[1];
  const aname =
    content.match(/<AssemblyName[^>]*>([^<]+)<\/AssemblyName>/)?.[1] ?? basename(resolved, ext);

  return {
    projectPath: resolved,
    language,
    targetFramework: tfm,
    assemblyName: aname,
    sourceFiles: [],
  };
}

// ─── XML Doc Parsing ───────────────────────────────────────────────────────

/**
 * Parse .NET XML documentation content into structured members.
 *
 * Expected XML format:
 * <doc>
 *   <assembly><name>AssemblyName</name></assembly>
 *   <members>
 *     <member name="T:MyClass">
 *       <summary>Class description</summary>
 *     </member>
 *   </members>
 * </doc>
 */
export function parseDotNetXml(xmlContent: string): DotNetXmlDoc {
  const assemblyName = xmlContent.match(/<assembly>\s*<name>([^<]+)<\/name>\s*<\/assembly>/)?.[1];
  const members: DotNetXmlMember[] = [];

  const memberRegex = /<member\s+name="([^"]+)">([\s\S]*?)<\/member>/g;
  let match: RegExpExecArray | null;
  while ((match = memberRegex.exec(xmlContent)) !== null) {
    const memberName = match[1]!;
    const body = match[2]!;

    const summary = body.match(/<summary>([\s\S]*?)<\/summary>/)?.[1]?.trim();
    const returns = body.match(/<returns>([\s\S]*?)<\/returns>/)?.[1]?.trim();
    const remarks = body.match(/<remarks>([\s\S]*?)<\/remarks>/)?.[1]?.trim();
    const example = body.match(/<example>([\s\S]*?)<\/example>/)?.[1]?.trim();

    const params: { name: string; description?: string }[] = [];
    const paramRegex = /<param\s+name="([^"]+)">([\s\S]*?)<\/param>/g;
    let pm: RegExpExecArray | null;
    while ((pm = paramRegex.exec(body)) !== null) {
      params.push({ name: pm[1]!, description: pm[2]?.trim() || undefined });
    }

    members.push({
      name: memberName,
      summary: summary || undefined,
      params: params.length > 0 ? params : undefined,
      returns: returns || undefined,
      remarks: remarks || undefined,
      example: example || undefined,
    });
  }

  return { assemblyName, members };
}

/**
 * Find and parse an XML doc file generated by the .NET compiler.
 * Typically named {AssemblyName}.xml alongside the assembly.
 */
export function findXmlDocFile(projectDir: string, assemblyName?: string): string | null {
  if (!existsSync(projectDir)) return null;

  const entries = readdirSync(projectDir);
  const candidates: string[] = [];
  for (const entry of entries) {
    if (entry.endsWith(".xml") && !entry.startsWith(".")) {
      candidates.push(join(projectDir, entry));
    }
  }

  if (assemblyName) {
    const preferred = candidates.find((c) => basename(c, ".xml") === assemblyName);
    if (preferred) return preferred;
  }

  return candidates[0] ?? null;
}

// ─── .NET XML → AST conversion ─────────────────────────────────────────────

interface ClassAccumulator {
  fullName: string;
  shortName: string;
  summary?: string;
  members: DotNetXmlMember[];
}

/**
 * Split a .NET member name into its prefix and the qualified name body.
 * Member names look like "T:Namespace.Class" or "M:Namespace.Class.Method(System.String)".
 */
function splitMemberName(name: string): { prefix: string; body: string } | null {
  const match = name.match(/^([TMPFNE]):(.+)$/);
  if (!match) return null;
  return { prefix: match[1]!, body: match[2]! };
}

/**
 * Strip the argument list from a method body, e.g.
 * "Namespace.Class.Method(System.String)" → "Namespace.Class.Method".
 */
function stripArgs(body: string): string {
  const parenIdx = body.indexOf("(");
  return parenIdx >= 0 ? body.slice(0, parenIdx) : body;
}

/**
 * Convert .NET XML documentation members to astro-polyglot AST modules.
 */
export function dotNetXmlToAST(doc: DotNetXmlDoc): ASTModule[] {
  const modules: ASTModule[] = [];
  const classes = new Map<string, ClassAccumulator>();

  for (const member of doc.members) {
    const parts = splitMemberName(member.name);
    if (!parts) continue;

    const { prefix, body } = parts;

    if (prefix === "T") {
      const segments = body.split(".");
      const shortName = segments[segments.length - 1] ?? body;
      if (!classes.has(body)) {
        classes.set(body, { fullName: body, shortName, summary: member.summary, members: [] });
      } else {
        const existing = classes.get(body)!;
        existing.summary = member.summary;
      }
      continue;
    }

    // Methods, properties, and fields attach to their declaring type.
    const declaringType = stripArgs(body).split(".").slice(0, -1).join(".");
    if (!declaringType) continue;

    let acc = classes.get(declaringType);
    if (!acc) {
      const segs = declaringType.split(".");
      const shortName = segs[segs.length - 1] ?? declaringType;
      acc = { fullName: declaringType, shortName, members: [] };
      classes.set(declaringType, acc);
    }
    acc.members.push(member);
  }

  for (const [, data] of classes) {
    const cls: ASTClass = {
      name: data.shortName,
      docstring: data.summary,
      methods: [],
      properties: [],
    };

    for (const member of data.members) {
      const parts = splitMemberName(member.name);
      const prefix = parts?.prefix;
      const body = parts?.body ?? member.name;
      const memberShort = stripArgs(body).split(".").pop() ?? body;

      if (prefix === "M") {
        cls.methods!.push({
          name: memberShort,
          docstring: member.summary,
          parameters: member.params?.map((p) => ({
            name: p.name,
            description: p.description,
          })),
          return_type: member.returns,
        });
      } else if (prefix === "P" || prefix === "F") {
        cls.properties!.push({
          name: memberShort,
          docstring: member.summary,
          ...(member.returns ? { type: member.returns } : {}),
        });
      }
    }

    modules.push({
      name: `${doc.assemblyName ?? "Assembly"}.${data.shortName}`,
      docstring: data.summary,
      classes: [cls],
      functions: [],
    });
  }

  return modules;
}
