/**
 * astro-polyglot — Doxygen Utilities
 *
 * Shared utilities for Doxygen-backed language handlers.
 * Provides Doxyfile generation and XML-to-AST transformation
 * reused by 13+ languages (C, C++, Objective-C, Ada, Fortran,
 * Pascal, COBOL, VHDL, Verilog, Tcl, IDL, Lex/Flex, Yacc/Bison).
 *
 * @module core/doxygen-utils
 */

import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { randomBytes } from "node:crypto";
import type { ASTClass, ASTModule, ASTParameter } from "./mdx-generator";

// ─── Types ─────────────────────────────────────────────────────────────────

export interface DoxygenConfig {
  /** Project name (default: "API Reference") */
  projectName?: string;
  /** Source directory containing the files to document */
  inputDir: string;
  /** File patterns to include (default: ["*.h", "*.hpp", "*.c", "*.cpp", "*.mm"]) */
  filePatterns?: string[];
  /** Extra Doxygen configuration lines */
  extraConfig?: string[];
  /** Doxygen binary path (default: "doxygen") */
  doxygenBin?: string;
}

export interface DoxygenCompound {
  kind: string;
  name: string;
  brief?: string;
  description?: string;
  templateParams?: string[];
  compounds?: DoxygenCompound[];
  sections?: DoxygenSection[];
  location?: { file: string; line?: number };
}

export interface DoxygenSection {
  kind: string;
  members: DoxygenMember[];
}

export interface DoxygenMember {
  name: string;
  brief?: string;
  description?: string;
  definition?: string;
  args?: string;
  type?: string;
  params?: { name: string; description?: string }[];
  location?: { file: string; line?: number };
}

// ─── Doxyfile Generation ───────────────────────────────────────────────────

/**
 * Generate a Doxyfile configuration string for the given project.
 */
export function generateDoxyfile(config: DoxygenConfig): string {
  const projectName = config.projectName ?? "API Reference";
  const filePatterns = config.filePatterns ?? ["*.h", "*.hpp", "*.c", "*.cpp", "*.mm"];
  const extraConfig = config.extraConfig ?? [];

  const lines: string[] = [
    `PROJECT_NAME           = "${projectName}"`,
    `PROJECT_BRIEF          = "Generated by astro-polyglot"`,
    `OUTPUT_DIRECTORY       = doxygen_output`,
    `GENERATE_XML           = YES`,
    `GENERATE_HTML          = NO`,
    `GENERATE_LATEX         = NO`,
    `QUIET                  = YES`,
    `WARNINGS               = NO`,
    `WARN_IF_UNDOCUMENTED   = NO`,
    `WARN_NO_PARAMDOC       = NO`,
    `RECURSIVE              = YES`,
    `EXTRACT_ALL            = YES`,
    `EXTRACT_PRIVATE        = YES`,
    `EXTRACT_STATIC         = YES`,
    `EXTRACT_LOCAL_CLASSES  = YES`,
    `HIDE_UNDOC_MEMBERS     = NO`,
    `HIDE_UNDOC_CLASSES     = NO`,
    `INPUT                  = ${config.inputDir}`,
    `FILE_PATTERNS          = ${filePatterns.join(" ")}`,
    `INPUT_ENCODING         = UTF-8`,
    `SOURCE_BROWSER         = NO`,
    `INLINE_SOURCES         = NO`,
    `STRIP_CODE_COMMENTS    = NO`,
    `CASE_SENSE_NAMES       = YES`,
    `SORT_MEMBER_DOCS       = YES`,
    `SORT_BRIEF_DOCS        = YES`,
    `ALPHABETICAL_INDEX     = NO`,
    `GENERATE_TAGFILE       = NO`,
    `JAVADOC_AUTOBRIEF      = YES`,
    `QT_AUTOBRIEF           = YES`,
    `MULTILINE_CPP_IS_BRIEF = YES`,
    `BUILTIN_STL_SUPPORT    = YES`,
    `ENABLE_PREPROCESSING   = YES`,
    `MACRO_EXPANSION        = YES`,
    ...extraConfig,
    "",
  ];

  return lines.join("\n");
}

/**
 * Write a Doxyfile to a temporary directory, run Doxygen, and return the
 * path to the generated XML output directory.
 * Returns `null` if Doxygen is not available or if generation fails.
 */
export async function runDoxygen(config: DoxygenConfig): Promise<string | null> {
  const doxygenBin = config.doxygenBin ?? "doxygen";

  try {
    execSync(`${doxygenBin} --version`, { encoding: "utf-8", stdio: "pipe", timeout: 10_000 });
  } catch {
    return null;
  }

  const workDir = resolve(tmpdir(), `astro-polyglot-doxygen-${randomBytes(4).toString("hex")}`);
  mkdirSync(workDir, { recursive: true });

  const doxyfile = generateDoxyfile({
    ...config,
    inputDir: resolve(config.inputDir),
  });

  writeFileSync(join(workDir, "Doxyfile"), doxyfile, "utf-8");

  try {
    execSync(doxygenBin, { cwd: workDir, encoding: "utf-8", stdio: "pipe", timeout: 60_000 });
    const xmlDir = join(workDir, "doxygen_output", "xml");
    if (!existsSync(xmlDir)) return null;
    return xmlDir;
  } catch {
    return null;
  }
}

// ─── XML Parsing Utilities ──────────────────────────────────────────────────

function extractTagContent(xml: string, tag: string): string | undefined {
  const match = xml.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`));
  return match?.[1]?.trim() || undefined;
}

function extractAllTags(xml: string, tag: string): string[] {
  const results: string[] = [];
  const regex = new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`, "g");
  let match: RegExpExecArray | null;
  while ((match = regex.exec(xml)) !== null) {
    results.push(match[1]!.trim());
  }
  return results;
}

function stripXml(xml: string): string {
  return xml.replace(/<[^>]+>/g, "").trim();
}

/**
 * Parse parameter descriptions from a member definition's detailed description.
 * Doxygen emits `<parameterlist><parameteritem>...<parameternamelist><parametername>...`
 */
function parseDoxygenParams(detailedDescription: string): { name: string; description?: string }[] {
  const params: { name: string; description?: string }[] = [];
  const paramList = extractAllTags(detailedDescription, "parameterlist");
  for (const paramItemRaw of paramList) {
    const paramItems = extractAllTags(paramItemRaw, "parameteritem");
    for (const item of paramItems) {
      const name = stripXml(extractTagContent(item, "parametername") ?? "");
      const desc = stripXml(extractTagContent(item, "parameterdescription") ?? "");
      if (name) {
        params.push({ name, description: desc || undefined });
      }
    }
  }
  return params;
}

/**
 * Parse a Doxygen compound definition XML into a structured DoxygenCompound.
 */
export function parseCompoundXml(xmlContent: string): DoxygenCompound {
  const kindMatch = /kind\s*=\s*"([^"]+)"/.exec(
    xmlContent.slice(xmlContent.indexOf("<compounddef"), xmlContent.indexOf(">", xmlContent.indexOf("<compounddef")) + 1),
  );
  const kind = kindMatch?.[1] ?? "class";
  const name = extractTagContent(xmlContent, "compoundname") ?? "Unknown";
  const brief = stripXml(extractTagContent(xmlContent, "briefdescription") ?? "");
  const detailed = extractTagContent(xmlContent, "detaileddescription") ?? "";

  const sections: DoxygenSection[] = [];
  const sectionDefs = extractAllTags(xmlContent, "sectiondef");

  for (const sectionDef of sectionDefs) {
    const sectionKind = sectionDef.match(/kind\s*=\s*"([^"]+)"/)?.[1] ?? "public-func";
    const members: DoxygenMember[] = [];
    const memberDefs = extractAllTags(sectionDef, "memberdef");

    for (const memberDef of memberDefs) {
      const memberKind = memberDef.match(/kind\s*=\s*"([^"]+)"/)?.[1] ?? "function";
      const memberName = extractTagContent(memberDef, "name") ?? "unknown";
      const memberBrief = stripXml(extractTagContent(memberDef, "briefdescription") ?? "");
      const memberDetailedRaw = extractTagContent(memberDef, "detaileddescription") ?? "";
      const memberDetailed = stripXml(memberDetailedRaw);
      const definition = extractTagContent(memberDef, "definition");
      const args = extractTagContent(memberDef, "argsstring");
      const type = stripXml(extractTagContent(memberDef, "type") ?? "");
      const params = parseDoxygenParams(memberDetailedRaw);

      if (memberKind === "function" || memberKind === "slot" || memberKind === "signal") {
        members.push({
          name: memberName,
          brief: memberBrief || undefined,
          description: memberDetailed || undefined,
          definition: definition ?? undefined,
          args: args ?? undefined,
          type: type || "void",
          params: params.length > 0 ? params : undefined,
        });
      } else if (memberKind === "variable") {
        members.push({
          name: memberName,
          brief: memberBrief || undefined,
          description: memberDetailed || undefined,
          type: type || undefined,
        });
      }
    }

    if (members.length > 0) {
      sections.push({ kind: sectionKind, members });
    }
  }

  return {
    kind,
    name,
    brief: brief || undefined,
    description: detailed ? stripXml(detailed) : undefined,
    sections: sections.length > 0 ? sections : undefined,
  };
}

/**
 * Parse all compound XML files in a Doxygen XML output directory.
 */
export function parseDoxygenXmlDir(xmlDir: string): DoxygenCompound[] {
  const compounds: DoxygenCompound[] = [];
  if (!existsSync(xmlDir)) return compounds;

  const files = readdirSync(xmlDir);
  for (const file of files) {
    if (!file.endsWith(".xml")) continue;
    const filePath = join(xmlDir, file);
    const content = readFileSync(filePath, "utf-8");
    if (!content.includes("<compounddef")) continue;
    try {
      compounds.push(parseCompoundXml(content));
    } catch {}
  }
  return compounds;
}

// ─── Doxygen → AST conversion ──────────────────────────────────────────────

/**
 * Convert a list of Doxygen compounds to astro-polyglot AST modules.
 */
export function doxygenToAST(compounds: DoxygenCompound[], _language?: string): ASTModule[] {
  const modules: ASTModule[] = [];

  for (const compound of compounds) {
    const docstring = compound.brief
      ? compound.description
        ? `${compound.brief}\n\n${compound.description}`
        : compound.brief
      : compound.description;

    const cls: ASTClass = {
      name: compound.name,
      docstring,
      methods: [],
      properties: [],
    };

    for (const section of compound.sections ?? []) {
      for (const member of section.members) {
        if (member.params || member.definition) {
          const parameters: ASTParameter[] | undefined = member.params?.map((p) => ({
            name: p.name,
            description: p.description,
          }));
          const memberDoc = member.brief
            ? member.description
              ? `${member.brief}\n\n${member.description}`
              : member.brief
            : member.description;
          cls.methods!.push({
            name: member.name,
            signature: member.definition ?? member.args,
            docstring: memberDoc,
            parameters,
            return_type: member.type && member.type !== "void" ? member.type : undefined,
          });
        } else {
          cls.properties!.push({
            name: member.name,
            type: member.type,
            docstring: member.brief ?? member.description,
          });
        }
      }
    }

    modules.push({
      name: compound.name,
      docstring,
      classes: (cls.methods?.length ?? 0) > 0 || (cls.properties?.length ?? 0) > 0 ? [cls] : [],
      functions: [],
    });
  }

  return modules;
}
